Calling thrower
Constructing
In catch
object(Exception) (8) {
  ["message":protected]=>
  string(7) "finally"
  ["string":"Exception":private]=>
  string(0) ""
  ["code":protected]=>
  int(0)
  ["file":protected]=>
  string(%d) "%s/test/slow/exceptions/chain-fault.php"
  ["line":protected]=>
  int(15)
  ["trace":"Exception":private]=>
  array(2) {
    [0]=>
    array(4) {
      ["file"]=>
      string(%d) "%s/test/slow/exceptions/chain-fault.php"
      ["line"]=>
      int(22)
      ["function"]=>
      string(7) "thrower"
      ["args"]=>
      array(0) {
      }
    }
    [1]=>
    array(2) {
      ["function"]=>
      string(4) "main"
      ["args"]=>
      array(0) {
      }
    }
  }
  ["previous":"Exception":private]=>
  object(LogExn) (8) {
    ["message":protected]=>
    string(5) "inner"
    ["string":"Exception":private]=>
    string(0) ""
    ["code":protected]=>
    int(0)
    ["file":protected]=>
    string(%d) "%s/test/slow/exceptions/chain-fault.php"
    ["line":protected]=>
    int(13)
    ["trace":"Exception":private]=>
    array(2) {
      [0]=>
      array(4) {
        ["file"]=>
        string(%d) "%s/test/slow/exceptions/chain-fault.php"
        ["line"]=>
        int(22)
        ["function"]=>
        string(7) "thrower"
        ["args"]=>
        array(0) {
        }
      }
      [1]=>
      array(2) {
        ["function"]=>
        string(4) "main"
        ["args"]=>
        array(0) {
        }
      }
    }
    ["previous":"Exception":private]=>
    NULL
    ["userMetadata":protected]=>
    NULL
  }
  ["userMetadata":protected]=>
  NULL
}
Leaving main
